version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:secretpassword@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  scraping:
    build: ./python-scrapping
    container_name: python-app
    working_dir: /usr/src/app
    volumes:
      - ./python-scrapping:/usr/src/app
      - ./downloads:/usr/src/app/downloads
    command: python3 src/main.py
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASS=secretpassword

  api:
    build: ./node-api
    container_name: api
    working_dir: /usr/src/app
    volumes:
      - ./node-api:/usr/src/app
    command: npm run dev
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://admin:secretpassword@mongo:27017/
      - PORT=3000
      - JWT_SECRET=47bce5c74f589f4867dbd57e9ca9f808
      - USERNAME=devmarcell
      - PASSWORD=47bce5c74f589f4867dbd57e9ca9f808

volumes:
  mongo_data:
